server:
   port: 8080
spring:
   application:
      name: gateway
   redis:
      host: localhost
      port: 6379
      database: 0
   cloud:
      gateway:
         httpclient:
            connect-timeout: 1000
            response-timeout: 5s

eureka:
   client:
      service-url:
         defaultZone: http://localhost:9000/eureka/

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000